/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8892263f-96c1-4829-b89d-f602936e8158",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "0bf55fdf6da3407190c60e0a6c0d6a5d",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
