import React, { useEffect, useState, useCallback } from "react";
// import Call from "../Call/Call";
// import StartButton from "../StartButton/StartButton";
// import api from "../../api";
import "./video_chat_styles.scss";
import Tray from "../Tray/Tray";
// import CallObjectContext from "../../CallObjectContext";
// import { roomUrlFromPageUrl, pageUrlFromRoomUrl } from "../../urlUtils";
// import DailyIframe from "@daily-co/daily-js";
// import { logDailyEvent } from "../../logUtils";
